["package"]
name = "amble"
description = "First class, scalable rust project generator with batteries included."
version = "0.1.14"
edition = "2021"
license = "MIT"
authors = ["refcell"]
rust-version = "1.72"
keywords = ["amble", "generator", "template", "scaffold", "cli"]
categories = ["command-line-utilities"]
homepage = "https://github.com/refcell/amble"
repository = "https://github.com/refcell/amble"
exclude = ["benches/", "tests/"]

[[bin]]
bench = false
path = "src/main.rs"
name = "amble"

[dependencies]
semver = "1.0.20"
regex = "1.10.2"
whoami = "1.4.1"
eyre = "0.6.8"
ptree = "0.4.0"
inquire = "0.6.2"
tracing = "0.1.40"
tracing-subscriber = "0.3.17"
clap = { version = "4.4.6", features = ["derive"] }
toml_edit = "0.20.2"
tokio = { version = "1.11.0", features = ["full"] }
serde_json = "1.0.107"
reqwest = { version = "0.11.22", features = ["blocking", "json"] }
chrono = "0.4.31"
gitignores = "2.3.2"

[dev-dependencies]
tempfile = "3.8.0"

[profile.dev]
opt-level = 1
overflow-checks = false

[profile.bench]
debug = true
