[package]
name = "amble"
description = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }

[[bin]]
bench = false
path = "src/main.rs"
name = "amble"

[dependencies]
anyhow = { workspace = true }
ptree = { workspace = true }
inquire = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { version = "4.4", features = ["derive"] }

preamble = { version = "0.1", path = "../../crates/preamble" }
