name: Github Release 

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: 
      - completed

jobs:
  fetch-latest-tag:
    name: Fetch the latest published git tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: WyriHaximus/github-action-get-previous-tag@v1
        id: previoustag
      - name: Extract the git tag version
        run: echo "TAG=${{ steps.previoustag.outputs.tag }}" >> $GITHUB_OUTPUT
        id: extract_git_version
    outputs:
      TAG: ${{ steps.extract_git_version.outputs.TAG }}

  release:
    name: Release on Github
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [fetch-latest-tag]
    env:
      TAG: ${{ needs.fetch-latest-tag.outputs.TAG }}
    steps:
    - uses: actions/checkout@v4
    - name: Build the target directory
      run: cargo build --release
    - name: Generate the Release Tarball
      run: tar --directory=target/release -cf release.tar.gz $(ls -U target/release/ | head -1)
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.tar.gz"
        tag: ${{ env.TAG }}
