name: Validate Release Version

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  extract-github-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: WyriHaximus/github-action-get-previous-tag@v1
        id: previoustag
      - name: Extract the git tag version
        run: echo "VERSION=$(echo ${{ steps.previoustag.outputs.tag }} | sed 's/^.*[^0-9]\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/')" >> $GITHUB_OUTPUT
        id: extract_git_version
    outputs:
      VERSION: ${{ steps.extract_git_version.outputs.VERSION }}

  extract-crate-package-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Export Crate Package Version
        run: echo "PACKAGEV=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version')" >> $GITHUB_OUTPUT
        id: export_crate_package_version
    outputs:
      PACKAGEV: ${{ steps.export_crate_package_version.outputs.PACKAGEV }}

  validate-crate-package-version:
    name: Validates that the crate package version is greater than the github tag version
    runs-on: ubuntu-latest
    needs: [extract-github-tag, extract-crate-package-version]
    env:
      VERSION: ${{ needs.extract-github-tag.outputs.VERSION }}
      PACKAGEV: ${{ needs.extract-crate-package-version.outputs.PACKAGEV }}
    steps:
      - uses: baptiste0928/cargo-install@v2
        with:
          crate: semver-util
      - name: Validate Semvers
        run: semver cmp ${{ env.PACKAGEV }} gt ${{ env.VERSION }} || exit 1
